name: Node Release

on:
  push:
    tags: '*'
  workflow_dispatch:

jobs:
  publish:
    uses: krauters/shared-workflows/.github/workflows/node-publish.yaml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
